# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bolddeskSDK_iOS_sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'bolddesk_support_sdk', '~> 1.0.0'

end
